from .about import *  # noqa
from .news import *  # noqa
from .exhibit import *  # noqa
from .exhibit_type import *  # noqa
from .image import *  # noqa
from .galery import *  # noqa
from .connect import *  # noqa
from .events import *  # noqa
from .event_type import *  # noqa
from .management import *  # noqa
from .supporters import *  # noqa
from .symbol import *  # noqa
from .video_gallery import *  # noqa
from .product import *  # noqa
from .museum_history import *  # noqa
from .price_section import *  # noqa
from .useful_content import *  # noqa
from .working_time import *  # noqa
from .social_media import *  # noqa
