# Generated by Django 5.0.7 on 2024-08-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("http", "0002_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="frontendtranslation",
            name="value_uz_cyrl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="desc_uz_cyrl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_uz_cyrl",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
