# Generated by Django 5.0.7 on 2024-08-05 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "http",
            "0003_frontendtranslation_value_uz_cyrl_post_desc_uz_cyrl_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="frontendtranslation",
            old_name="value_uz_cyrl",
            new_name="value_уз",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="desc_uz_cyrl",
            new_name="desc_уз",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="title_uz_cyrl",
            new_name="title_уз",
        ),
    ]
