# Generated by Django 5.0.7 on 2024-08-05 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "http",
            "0004_rename_value_uz_cyrl_frontendtranslation_value_уз_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="frontendtranslation",
            name="value_уз",
        ),
        migrations.RemoveField(
            model_name="post",
            name="desc_уз",
        ),
        migrations.RemoveField(
            model_name="post",
            name="title_уз",
        ),
    ]
