# Generated by Django 5.0.7 on 2024-08-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("http", "0005_remove_frontendtranslation_value_уз_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="frontendtranslation",
            name="value_uz_Cyrl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="desc_uz_Cyrl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title_uz_Cyrl",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
