# Generated by Django 5.0.7 on 2024-07-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="Exhibit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("material", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=255)),
                ("size", models.CharField(max_length=255)),
                ("image", models.ManyToManyField(to="museum.image")),
            ],
            options={
                "verbose_name": "Exhibit",
                "verbose_name_plural": "Exhibits",
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ManyToManyField(to="museum.image")),
            ],
            options={
                "verbose_name": "Gallery",
                "verbose_name_plural": "Galleries",
            },
        ),
    ]
