# Generated by Django 5.0.7 on 2024-07-31 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0002_image_name_exhibit_gallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=25)),
                ("massage", models.TextField()),
            ],
            options={
                "verbose_name": "Connect",
                "verbose_name_plural": "Connects",
            },
        ),
    ]
