# Generated by Django 5.0.7 on 2024-07-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0003_connect"),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("theme", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("date", models.DateTimeField()),
                ("image", models.ManyToManyField(to="museum.image")),
            ],
            options={
                "verbose_name": "Events",
                "verbose_name_plural": "Events",
            },
        ),
    ]
