# Generated by Django 5.0.7 on 2024-08-02 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0004_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name": "EventType",
                "verbose_name_plural": "EventType",
            },
        ),
        migrations.CreateModel(
            name="ExhibitType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name": "ExhibitType",
                "verbose_name_plural": "ExhibitType",
            },
        ),
        migrations.CreateModel(
            name="Management",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="team_images")),
                ("description", models.TextField()),
                ("phone", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Management",
                "verbose_name_plural": "Managements",
            },
        ),
        migrations.AddField(
            model_name="events",
            name="type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="museum.eventtype",
            ),
            preserve_default=False,
        ),
    ]
