# Generated by Django 5.0.7 on 2024-08-02 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0005_eventtype_exhibittype_management_events_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibit",
            name="type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="museum.exhibittype",
            ),
            preserve_default=False,
        ),
    ]
