# Generated by Django 5.0.7 on 2024-08-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0006_exhibit_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="description_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="description_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="theme_en",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="theme_ru",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="theme_uz",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="eventtype",
            name="name_en",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="eventtype",
            name="name_ru",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="eventtype",
            name="name_uz",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="color_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="color_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="color_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="description_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="description_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="material_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="material_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="material_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="name_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exhibittype",
            name="name_en",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="exhibittype",
            name="name_ru",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="exhibittype",
            name="name_uz",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="name_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="name_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="name_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="management",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="management",
            name="description_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="management",
            name="description_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="management",
            name="full_name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="management",
            name="full_name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="management",
            name="full_name_uz",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="management",
            name="position_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="management",
            name="position_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="management",
            name="position_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="text_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="text_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="text_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_uz",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
