# Generated by Django 5.0.7 on 2024-08-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "museum",
            "0007_events_description_en_events_description_ru_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="description_uz_cyrl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="events",
            name="theme_uz_cyrl",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="eventtype",
            name="name_uz_cyrl",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="color_uz_cyrl",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="description_uz_cyrl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="material_uz_cyrl",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="name_uz_cyrl",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="exhibittype",
            name="name_uz_cyrl",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="name_uz_cyrl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="management",
            name="description_uz_cyrl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="management",
            name="full_name_uz_cyrl",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="management",
            name="position_uz_cyrl",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="text_uz_cyrl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_uz_cyrl",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
