# Generated by Django 5.0.7 on 2024-08-05 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "museum",
            "0008_events_description_uz_cyrl_events_theme_uz_cyrl_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="events",
            old_name="description_uz_cyrl",
            new_name="description_уз",
        ),
        migrations.RenameField(
            model_name="events",
            old_name="theme_uz_cyrl",
            new_name="theme_уз",
        ),
        migrations.RenameField(
            model_name="eventtype",
            old_name="name_uz_cyrl",
            new_name="name_уз",
        ),
        migrations.RenameField(
            model_name="exhibit",
            old_name="color_uz_cyrl",
            new_name="color_уз",
        ),
        migrations.RenameField(
            model_name="exhibit",
            old_name="description_uz_cyrl",
            new_name="description_уз",
        ),
        migrations.RenameField(
            model_name="exhibit",
            old_name="material_uz_cyrl",
            new_name="material_уз",
        ),
        migrations.RenameField(
            model_name="exhibit",
            old_name="name_uz_cyrl",
            new_name="name_уз",
        ),
        migrations.RenameField(
            model_name="exhibittype",
            old_name="name_uz_cyrl",
            new_name="name_уз",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="name_uz_cyrl",
            new_name="name_уз",
        ),
        migrations.RenameField(
            model_name="management",
            old_name="description_uz_cyrl",
            new_name="description_уз",
        ),
        migrations.RenameField(
            model_name="management",
            old_name="full_name_uz_cyrl",
            new_name="full_name_уз",
        ),
        migrations.RenameField(
            model_name="management",
            old_name="position_uz_cyrl",
            new_name="position_уз",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="text_uz_cyrl",
            new_name="text_уз",
        ),
        migrations.RenameField(
            model_name="news",
            old_name="title_uz_cyrl",
            new_name="title_уз",
        ),
    ]
