# Generated by Django 5.0.7 on 2024-08-05 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "museum",
            "0009_rename_description_uz_cyrl_events_description_уз_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="events",
            name="description_уз",
        ),
        migrations.RemoveField(
            model_name="events",
            name="theme_уз",
        ),
        migrations.RemoveField(
            model_name="eventtype",
            name="name_уз",
        ),
        migrations.RemoveField(
            model_name="exhibit",
            name="color_уз",
        ),
        migrations.RemoveField(
            model_name="exhibit",
            name="description_уз",
        ),
        migrations.RemoveField(
            model_name="exhibit",
            name="material_уз",
        ),
        migrations.RemoveField(
            model_name="exhibit",
            name="name_уз",
        ),
        migrations.RemoveField(
            model_name="exhibittype",
            name="name_уз",
        ),
        migrations.RemoveField(
            model_name="image",
            name="name_уз",
        ),
        migrations.RemoveField(
            model_name="management",
            name="description_уз",
        ),
        migrations.RemoveField(
            model_name="management",
            name="full_name_уз",
        ),
        migrations.RemoveField(
            model_name="management",
            name="position_уз",
        ),
        migrations.RemoveField(
            model_name="news",
            name="text_уз",
        ),
        migrations.RemoveField(
            model_name="news",
            name="title_уз",
        ),
    ]
