# Generated by Django 5.0.7 on 2024-08-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "museum",
            "0011_events_description_uz_cyrl_events_theme_uz_cyrl_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Supporters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(upload_to="museum_supporters")),
            ],
            options={
                "verbose_name": "Supporter",
                "verbose_name_plural": "Supporters",
            },
        ),
    ]
