# Generated by Django 5.0.7 on 2024-08-06 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0012_supporters"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="museum_about")),
                ("title", models.CharField(max_length=300)),
                ("title_uz", models.CharField(max_length=300, null=True)),
                ("title_uz_Cyrl", models.CharField(max_length=300, null=True)),
                ("title_ru", models.CharField(max_length=300, null=True)),
                ("title_en", models.CharField(max_length=300, null=True)),
                ("text", models.TextField()),
                ("text_uz", models.TextField(null=True)),
                ("text_uz_Cyrl", models.TextField(null=True)),
                ("text_ru", models.TextField(null=True)),
                ("text_en", models.TextField(null=True)),
                ("phone", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=100)),
                ("region_uz", models.CharField(max_length=100, null=True)),
                (
                    "region_uz_Cyrl",
                    models.CharField(max_length=100, null=True),
                ),
                ("region_ru", models.CharField(max_length=100, null=True)),
                ("region_en", models.CharField(max_length=100, null=True)),
                ("district", models.CharField(max_length=100)),
                ("district_uz", models.CharField(max_length=100, null=True)),
                (
                    "district_uz_Cyrl",
                    models.CharField(max_length=100, null=True),
                ),
                ("district_ru", models.CharField(max_length=100, null=True)),
                ("district_en", models.CharField(max_length=100, null=True)),
                ("street", models.CharField(max_length=100)),
                ("street_uz", models.CharField(max_length=100, null=True)),
                (
                    "street_uz_Cyrl",
                    models.CharField(max_length=100, null=True),
                ),
                ("street_ru", models.CharField(max_length=100, null=True)),
                ("street_en", models.CharField(max_length=100, null=True)),
                ("home", models.CharField(max_length=100)),
                ("home_uz", models.CharField(max_length=100, null=True)),
                ("home_uz_Cyrl", models.CharField(max_length=100, null=True)),
                ("home_ru", models.CharField(max_length=100, null=True)),
                ("home_en", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_uz", models.CharField(max_length=255, null=True)),
                ("name_uz_Cyrl", models.CharField(max_length=255, null=True)),
                ("name_ru", models.CharField(max_length=255, null=True)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("image", models.ImageField(upload_to="symbols/")),
                ("description", models.TextField()),
                ("description_uz", models.TextField(null=True)),
                ("description_uz_Cyrl", models.TextField(null=True)),
                ("description_ru", models.TextField(null=True)),
                ("description_en", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_uz", models.CharField(max_length=255, null=True)),
                ("name_uz_Cyrl", models.CharField(max_length=255, null=True)),
                ("name_ru", models.CharField(max_length=255, null=True)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="museum.address",
                    ),
                ),
            ],
        ),
    ]
