# Generated by Django 5.0.7 on 2024-08-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0014_producttype_videogallery_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="desc_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="desc_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="desc_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="desc_uz_Cyrl",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_uz_Cyrl",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="producttype",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="producttype",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="producttype",
            name="name_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="producttype",
            name="name_uz_Cyrl",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
