# Generated by Django 5.1 on 2024-08-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "museum",
            "0015_product_desc_en_product_desc_ru_product_desc_uz_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="name",
        ),
        migrations.RemoveField(
            model_name="image",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="image",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="image",
            name="name_uz",
        ),
        migrations.RemoveField(
            model_name="image",
            name="name_uz_Cyrl",
        ),
    ]
