# Generated by Django 5.1 on 2024-08-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0016_remove_image_name_remove_image_name_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MuseumHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("text", models.TextField()),
                ("image", models.ImageField(upload_to="museum_history/")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
