# Generated by Django 5.1 on 2024-08-13 07:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0017_museumhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="museumhistory",
            name="text",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
