# Generated by Django 5.1 on 2024-08-15 12:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0018_alter_museumhistory_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="museumhistory",
            name="image",
        ),
        migrations.RemoveField(
            model_name="museumhistory",
            name="title",
        ),
        migrations.RemoveField(
            model_name="news",
            name="image",
        ),
        migrations.RemoveField(
            model_name="news",
            name="title",
        ),
        migrations.RemoveField(
            model_name="news",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="news",
            name="title_ru",
        ),
        migrations.RemoveField(
            model_name="news",
            name="title_uz",
        ),
        migrations.RemoveField(
            model_name="news",
            name="title_uz_Cyrl",
        ),
        migrations.AlterField(
            model_name="news",
            name="text",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="news",
            name="text_en",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="text_ru",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="text_uz",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="text_uz_Cyrl",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
