# Generated by Django 5.1 on 2024-08-15 12:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0019_remove_museumhistory_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="museumhistory",
            name="text_en",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="museumhistory",
            name="text_ru",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="museumhistory",
            name="text_uz",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="museumhistory",
            name="text_uz_Cyrl",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
