# Generated by Django 5.1 on 2024-08-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "museum",
            "0020_museumhistory_text_en_museumhistory_text_ru_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.ManyToManyField(to="museum.image"),
        ),
        migrations.AddField(
            model_name="news",
            name="title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="news",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="news",
            name="text_en",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="text_ru",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="text_uz",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="news",
            name="text_uz_Cyrl",
            field=models.TextField(null=True),
        ),
    ]
