# Generated by Django 5.1 on 2024-08-16 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0021_news_image_news_title_alter_news_text_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_uz", models.CharField(max_length=255, null=True)),
                ("title_uz_Cyrl", models.CharField(max_length=255, null=True)),
                ("title_ru", models.CharField(max_length=255, null=True)),
                ("title_en", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UsefulContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="useful_content_images/"),
                ),
                ("definition", models.TextField()),
                ("definition_uz", models.TextField(null=True)),
                ("definition_uz_Cyrl", models.TextField(null=True)),
                ("definition_ru", models.TextField(null=True)),
                ("definition_en", models.TextField(null=True)),
                ("url", models.URLField()),
                ("url_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="WorkingTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekday", models.CharField(max_length=30)),
                ("weekday_uz", models.CharField(max_length=30, null=True)),
                (
                    "weekday_uz_Cyrl",
                    models.CharField(max_length=30, null=True),
                ),
                ("weekday_ru", models.CharField(max_length=30, null=True)),
                ("weekday_en", models.CharField(max_length=30, null=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
            options={
                "verbose_name": "Working Time",
                "verbose_name_plural": "Working Times",
                "ordering": ["weekday"],
            },
        ),
        migrations.CreateModel(
            name="PriceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "description_uz",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "description_uz_Cyrl",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "description_ru",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "description_en",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "quantity",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("price", models.CharField(max_length=255)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="museum.pricesection",
                    ),
                ),
            ],
        ),
    ]
