# Generated by Django 5.1 on 2024-08-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0022_pricesection_usefulcontent_workingtime_priceitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name="management",
            name="phone",
        ),
        migrations.AddField(
            model_name="management",
            name="phone",
            field=models.ManyToManyField(to="museum.phone"),
        ),
    ]
