# Generated by Django 5.1 on 2024-08-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0023_phone_remove_management_phone_management_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="videogallery",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="video_image/"
            ),
        ),
        migrations.RemoveField(
            model_name="about",
            name="phone",
        ),
        migrations.AddField(
            model_name="about",
            name="phone",
            field=models.ManyToManyField(to="museum.phone"),
        ),
    ]
