# Generated by Django 5.1 on 2024-08-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0024_videogallery_image_remove_about_phone_about_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="title_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_uz_Cyrl",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
