# Generated by Django 5.1 on 2024-08-16 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0025_news_title_en_news_title_ru_news_title_uz_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_uz", models.CharField(max_length=200, null=True)),
                ("name_uz_Cyrl", models.CharField(max_length=200, null=True)),
                ("name_ru", models.CharField(max_length=200, null=True)),
                ("name_en", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="news",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="museum.newstype",
            ),
        ),
    ]
