# Generated by Django 5.1 on 2024-08-16 10:08

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0026_newstype_news_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="museumhistory",
            name="text_en",
        ),
        migrations.RemoveField(
            model_name="museumhistory",
            name="text_ru",
        ),
        migrations.RemoveField(
            model_name="museumhistory",
            name="text_uz",
        ),
        migrations.RemoveField(
            model_name="museumhistory",
            name="text_uz_Cyrl",
        ),
        migrations.AlterField(
            model_name="museumhistory",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
    ]
