# Generated by Django 5.1 on 2024-08-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0027_remove_museumhistory_text_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="museumhistory",
            name="text",
            field=models.TextField(),
        ),
    ]
