# Generated by Django 5.1 on 2024-08-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0028_alter_museumhistory_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="museumhistory",
            name="text_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="museumhistory",
            name="text_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="museumhistory",
            name="text_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="museumhistory",
            name="text_uz_Cyrl",
            field=models.TextField(null=True),
        ),
    ]
