# Generated by Django 5.1 on 2024-08-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "museum",
            "0029_museumhistory_text_en_museumhistory_text_ru_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="social_icons/"
                    ),
                ),
            ],
        ),
    ]
