# Generated by Django 5.1 on 2024-08-23 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0030_socialmedia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="about",
            options={
                "verbose_name": "Haqida",
                "verbose_name_plural": "Haqida",
            },
        ),
        migrations.AlterModelOptions(
            name="address",
            options={
                "verbose_name": "Manzil",
                "verbose_name_plural": "Manzillar",
            },
        ),
        migrations.AlterModelOptions(
            name="connect",
            options={
                "verbose_name": "Bog'lanish",
                "verbose_name_plural": "Bog'lanishlar",
            },
        ),
        migrations.AlterModelOptions(
            name="events",
            options={
                "verbose_name": "Tadbir",
                "verbose_name_plural": "Tadbirlar",
            },
        ),
        migrations.AlterModelOptions(
            name="eventtype",
            options={
                "verbose_name": "Tadbir turi",
                "verbose_name_plural": "Tadbir turlari",
            },
        ),
        migrations.AlterModelOptions(
            name="exhibit",
            options={
                "verbose_name": "Eksponat",
                "verbose_name_plural": "Eksponatlar",
            },
        ),
        migrations.AlterModelOptions(
            name="exhibittype",
            options={
                "verbose_name": "Eksponat turi",
                "verbose_name_plural": "Eksponat turlari",
            },
        ),
        migrations.AlterModelOptions(
            name="gallery",
            options={
                "verbose_name": "Galereya",
                "verbose_name_plural": "Galereyalar",
            },
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name": "Rasm", "verbose_name_plural": "Rasmlar"},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={
                "verbose_name": "Joylashuv",
                "verbose_name_plural": "Joylashuvlar",
            },
        ),
        migrations.AlterModelOptions(
            name="management",
            options={
                "verbose_name": "Boshqaruv",
                "verbose_name_plural": "Boshqaruvchilar",
            },
        ),
        migrations.AlterModelOptions(
            name="museumhistory",
            options={
                "verbose_name": "Muzey tarixi",
                "verbose_name_plural": "Muzey tarixlari",
            },
        ),
        migrations.AlterModelOptions(
            name="news",
            options={
                "verbose_name": "Yangilik",
                "verbose_name_plural": "Yangiliklar",
            },
        ),
        migrations.AlterModelOptions(
            name="newstype",
            options={
                "verbose_name": "Yangilik turi",
                "verbose_name_plural": "Yangilik turlari",
            },
        ),
        migrations.AlterModelOptions(
            name="phone",
            options={
                "verbose_name": "Telefon",
                "verbose_name_plural": "Telefonlar",
            },
        ),
        migrations.AlterModelOptions(
            name="priceitem",
            options={
                "verbose_name": "Narx elementi",
                "verbose_name_plural": "Narx elementlari",
            },
        ),
        migrations.AlterModelOptions(
            name="pricesection",
            options={
                "verbose_name": "Narx bo'limi",
                "verbose_name_plural": "Narx bo'limlari",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "verbose_name": "Mahsulot",
                "verbose_name_plural": "Mahsulotlar",
            },
        ),
        migrations.AlterModelOptions(
            name="producttype",
            options={
                "verbose_name": "Mahsulot turi",
                "verbose_name_plural": "Mahsulot turlari",
            },
        ),
        migrations.AlterModelOptions(
            name="socialmedia",
            options={
                "verbose_name": "Ijtimoiy tarmoq",
                "verbose_name_plural": "Ijtimoiy tarmoqlar",
            },
        ),
        migrations.AlterModelOptions(
            name="supporters",
            options={
                "verbose_name": "Hamkor",
                "verbose_name_plural": "Hamkorlar",
            },
        ),
        migrations.AlterModelOptions(
            name="symbol",
            options={
                "verbose_name": "Davlat ramzi",
                "verbose_name_plural": "Davlat ramzlari",
            },
        ),
        migrations.AlterModelOptions(
            name="usefulcontent",
            options={
                "verbose_name": "Foydali kontent",
                "verbose_name_plural": "Foydali kontentlar",
            },
        ),
        migrations.AlterModelOptions(
            name="videogallery",
            options={
                "verbose_name": "Video galereya",
                "verbose_name_plural": "Video galereyalar",
            },
        ),
        migrations.AlterModelOptions(
            name="workingtime",
            options={
                "ordering": ["weekday"],
                "verbose_name": "Ish vaqti",
                "verbose_name_plural": "Ish vaqtlar",
            },
        ),
        migrations.AlterField(
            model_name="about",
            name="email",
            field=models.CharField(max_length=100, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="about",
            name="image",
            field=models.ImageField(
                upload_to="museum_about", verbose_name="Rasm"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="phone",
            field=models.ManyToManyField(
                to="museum.phone", verbose_name="Telefonlar"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="text",
            field=models.TextField(verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="about",
            name="text_en",
            field=models.TextField(null=True, verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="about",
            name="text_ru",
            field=models.TextField(null=True, verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="about",
            name="text_uz",
            field=models.TextField(null=True, verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="about",
            name="text_uz_Cyrl",
            field=models.TextField(null=True, verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="about",
            name="title",
            field=models.CharField(max_length=300, verbose_name="Sarlavha"),
        ),
        migrations.AlterField(
            model_name="about",
            name="title_en",
            field=models.CharField(
                max_length=300, null=True, verbose_name="Sarlavha"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="title_ru",
            field=models.CharField(
                max_length=300, null=True, verbose_name="Sarlavha"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="title_uz",
            field=models.CharField(
                max_length=300, null=True, verbose_name="Sarlavha"
            ),
        ),
        migrations.AlterField(
            model_name="about",
            name="title_uz_Cyrl",
            field=models.CharField(
                max_length=300, null=True, verbose_name="Sarlavha"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="district",
            field=models.CharField(max_length=100, verbose_name="Tuman"),
        ),
        migrations.AlterField(
            model_name="address",
            name="district_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Tuman"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="district_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Tuman"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="district_uz",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Tuman"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="district_uz_Cyrl",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Tuman"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="home",
            field=models.CharField(max_length=100, verbose_name="Uy"),
        ),
        migrations.AlterField(
            model_name="address",
            name="home_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Uy"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="home_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Uy"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="home_uz",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Uy"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="home_uz_Cyrl",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Uy"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="region",
            field=models.CharField(max_length=100, verbose_name="Viloyat"),
        ),
        migrations.AlterField(
            model_name="address",
            name="region_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Viloyat"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="region_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Viloyat"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="region_uz",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Viloyat"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="region_uz_Cyrl",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Viloyat"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.CharField(max_length=100, verbose_name="Ko'cha"),
        ),
        migrations.AlterField(
            model_name="address",
            name="street_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Ko'cha"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="street_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Ko'cha"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="street_uz",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Ko'cha"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="street_uz_Cyrl",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Ko'cha"
            ),
        ),
        migrations.AlterField(
            model_name="connect",
            name="massage",
            field=models.TextField(verbose_name="Xabar"),
        ),
        migrations.AlterField(
            model_name="connect",
            name="phone",
            field=models.CharField(max_length=25, verbose_name="Telefon"),
        ),
        migrations.AlterField(
            model_name="connect",
            name="user_name",
            field=models.CharField(
                max_length=100, verbose_name="Foydalanuvchi nomi"
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="date",
            field=models.DateTimeField(verbose_name="Sana"),
        ),
        migrations.AlterField(
            model_name="events",
            name="description",
            field=models.TextField(verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="events",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="events",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="events",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="events",
            name="description_uz_Cyrl",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="events",
            name="image",
            field=models.ManyToManyField(
                to="museum.image", verbose_name="Rasm(lar)"
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="theme",
            field=models.CharField(max_length=300, verbose_name="Mavzu"),
        ),
        migrations.AlterField(
            model_name="events",
            name="theme_en",
            field=models.CharField(
                max_length=300, null=True, verbose_name="Mavzu"
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="theme_ru",
            field=models.CharField(
                max_length=300, null=True, verbose_name="Mavzu"
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="theme_uz",
            field=models.CharField(
                max_length=300, null=True, verbose_name="Mavzu"
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="theme_uz_Cyrl",
            field=models.CharField(
                max_length=300, null=True, verbose_name="Mavzu"
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="museum.eventtype",
                verbose_name="Turi",
            ),
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="name_en",
            field=models.CharField(
                max_length=300, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="name_ru",
            field=models.CharField(
                max_length=300, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="name_uz",
            field=models.CharField(
                max_length=300, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="eventtype",
            name="name_uz_Cyrl",
            field=models.CharField(
                max_length=300, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="color",
            field=models.CharField(max_length=255, verbose_name="Rang"),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="color_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Rang"
            ),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="color_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Rang"
            ),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="color_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Rang"
            ),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="color_uz_Cyrl",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Rang"
            ),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="description",
            field=models.TextField(verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="description_uz_Cyrl",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="image",
            field=models.ManyToManyField(
                to="museum.image", verbose_name="Rasm(lar)"
            ),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="material",
            field=models.CharField(max_length=255, verbose_name="Material"),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="material_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Material"
            ),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="material_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Material"
            ),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="material_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Material"
            ),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="material_uz_Cyrl",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Material"
            ),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="name_uz_Cyrl",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="size",
            field=models.CharField(max_length=255, verbose_name="O'lcham"),
        ),
        migrations.AlterField(
            model_name="exhibit",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="museum.exhibittype",
                verbose_name="Turi",
            ),
        ),
        migrations.AlterField(
            model_name="exhibittype",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="exhibittype",
            name="name_en",
            field=models.CharField(
                max_length=300, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="exhibittype",
            name="name_ru",
            field=models.CharField(
                max_length=300, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="exhibittype",
            name="name_uz",
            field=models.CharField(
                max_length=300, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="exhibittype",
            name="name_uz_Cyrl",
            field=models.CharField(
                max_length=300, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="gallery",
            name="image",
            field=models.ManyToManyField(
                to="museum.image", verbose_name="Rasm(lar)"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                upload_to="museum_images", verbose_name="Rasm"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="museum.address",
                verbose_name="Manzil",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.FloatField(verbose_name="Kenglik"),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.FloatField(verbose_name="Uzunlik"),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="location",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name_uz_Cyrl",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="management",
            name="description",
            field=models.TextField(verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="management",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="management",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="management",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="management",
            name="description_uz_Cyrl",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="management",
            name="email",
            field=models.CharField(max_length=100, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="management",
            name="full_name",
            field=models.CharField(max_length=100, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name="management",
            name="full_name_en",
            field=models.CharField(
                max_length=100, null=True, verbose_name="To'liq ism"
            ),
        ),
        migrations.AlterField(
            model_name="management",
            name="full_name_ru",
            field=models.CharField(
                max_length=100, null=True, verbose_name="To'liq ism"
            ),
        ),
        migrations.AlterField(
            model_name="management",
            name="full_name_uz",
            field=models.CharField(
                max_length=100, null=True, verbose_name="To'liq ism"
            ),
        ),
        migrations.AlterField(
            model_name="management",
            name="full_name_uz_Cyrl",
            field=models.CharField(
                max_length=100, null=True, verbose_name="To'liq ism"
            ),
        ),
        migrations.AlterField(
            model_name="management",
            name="image",
            field=models.ImageField(
                upload_to="team_images", verbose_name="Rasm"
            ),
        ),
        migrations.AlterField(
            model_name="management",
            name="phone",
            field=models.ManyToManyField(
                to="museum.phone", verbose_name="Telefon(lar)"
            ),
        ),
        migrations.AlterField(
            model_name="management",
            name="position",
            field=models.CharField(max_length=255, verbose_name="Lavozim"),
        ),
        migrations.AlterField(
            model_name="management",
            name="position_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Lavozim"
            ),
        ),
        migrations.AlterField(
            model_name="management",
            name="position_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Lavozim"
            ),
        ),
        migrations.AlterField(
            model_name="management",
            name="position_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Lavozim"
            ),
        ),
        migrations.AlterField(
            model_name="management",
            name="position_uz_Cyrl",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Lavozim"
            ),
        ),
        migrations.AlterField(
            model_name="museumhistory",
            name="text",
            field=models.TextField(verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="museumhistory",
            name="text_en",
            field=models.TextField(null=True, verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="museumhistory",
            name="text_ru",
            field=models.TextField(null=True, verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="museumhistory",
            name="text_uz",
            field=models.TextField(null=True, verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="museumhistory",
            name="text_uz_Cyrl",
            field=models.TextField(null=True, verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.ManyToManyField(
                to="museum.image", verbose_name="Rasm(lar)"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="text",
            field=models.TextField(verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="news",
            name="text_en",
            field=models.TextField(null=True, verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="news",
            name="text_ru",
            field=models.TextField(null=True, verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="news",
            name="text_uz",
            field=models.TextField(null=True, verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="news",
            name="text_uz_Cyrl",
            field=models.TextField(null=True, verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Sarlavha"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sarlavha"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sarlavha"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sarlavha"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_uz_Cyrl",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sarlavha"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="museum.newstype",
                verbose_name="Turi",
            ),
        ),
        migrations.AlterField(
            model_name="newstype",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="newstype",
            name="name_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="newstype",
            name="name_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="newstype",
            name="name_uz",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="newstype",
            name="name_uz_Cyrl",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="phone",
            name="phone",
            field=models.CharField(max_length=30, verbose_name="Telefon"),
        ),
        migrations.AlterField(
            model_name="priceitem",
            name="description",
            field=models.CharField(max_length=255, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="priceitem",
            name="description_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Tavsif"
            ),
        ),
        migrations.AlterField(
            model_name="priceitem",
            name="description_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Tavsif"
            ),
        ),
        migrations.AlterField(
            model_name="priceitem",
            name="description_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Tavsif"
            ),
        ),
        migrations.AlterField(
            model_name="priceitem",
            name="description_uz_Cyrl",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Tavsif"
            ),
        ),
        migrations.AlterField(
            model_name="priceitem",
            name="price",
            field=models.CharField(max_length=255, verbose_name="Narx"),
        ),
        migrations.AlterField(
            model_name="priceitem",
            name="quantity",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Miqdor"
            ),
        ),
        migrations.AlterField(
            model_name="priceitem",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="museum.pricesection",
                verbose_name="Bo'lim",
            ),
        ),
        migrations.AlterField(
            model_name="pricesection",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Sarlavha"),
        ),
        migrations.AlterField(
            model_name="pricesection",
            name="title_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sarlavha"
            ),
        ),
        migrations.AlterField(
            model_name="pricesection",
            name="title_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sarlavha"
            ),
        ),
        migrations.AlterField(
            model_name="pricesection",
            name="title_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sarlavha"
            ),
        ),
        migrations.AlterField(
            model_name="pricesection",
            name="title_uz_Cyrl",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sarlavha"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="desc",
            field=models.TextField(verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="product",
            name="desc_en",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="product",
            name="desc_ru",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="product",
            name="desc_uz",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="product",
            name="desc_uz_Cyrl",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to="products/", verbose_name="Rasm"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_uz_Cyrl",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Narx"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="museum.producttype",
                verbose_name="Turi",
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="producttype",
            name="name_uz_Cyrl",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="social_icons/",
                verbose_name="Ikonka",
            ),
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="url",
            field=models.URLField(verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="supporters",
            name="logo",
            field=models.ImageField(
                upload_to="museum_supporters", verbose_name="Logo"
            ),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="description",
            field=models.TextField(verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="description_uz_Cyrl",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="image",
            field=models.ImageField(upload_to="symbols/", verbose_name="Rasm"),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="symbol",
            name="name_uz_Cyrl",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="usefulcontent",
            name="definition",
            field=models.TextField(verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="usefulcontent",
            name="definition_en",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="usefulcontent",
            name="definition_ru",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="usefulcontent",
            name="definition_uz",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="usefulcontent",
            name="definition_uz_Cyrl",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="usefulcontent",
            name="image",
            field=models.ImageField(
                upload_to="useful_content_images/", verbose_name="Rasm"
            ),
        ),
        migrations.AlterField(
            model_name="usefulcontent",
            name="url",
            field=models.URLField(verbose_name="URL"),
        ),
        migrations.AlterField(
            model_name="usefulcontent",
            name="url_name",
            field=models.CharField(max_length=255, verbose_name="URL nomi"),
        ),
        migrations.AlterField(
            model_name="videogallery",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="video_image/",
                verbose_name="Rasm",
            ),
        ),
        migrations.AlterField(
            model_name="videogallery",
            name="text",
            field=models.TextField(verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="videogallery",
            name="text_en",
            field=models.TextField(null=True, verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="videogallery",
            name="text_ru",
            field=models.TextField(null=True, verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="videogallery",
            name="text_uz",
            field=models.TextField(null=True, verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="videogallery",
            name="text_uz_Cyrl",
            field=models.TextField(null=True, verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="videogallery",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Sarlavha"),
        ),
        migrations.AlterField(
            model_name="videogallery",
            name="title_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sarlavha"
            ),
        ),
        migrations.AlterField(
            model_name="videogallery",
            name="title_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sarlavha"
            ),
        ),
        migrations.AlterField(
            model_name="videogallery",
            name="title_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sarlavha"
            ),
        ),
        migrations.AlterField(
            model_name="videogallery",
            name="title_uz_Cyrl",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sarlavha"
            ),
        ),
        migrations.AlterField(
            model_name="videogallery",
            name="video_url",
            field=models.URLField(verbose_name="Video URL"),
        ),
        migrations.AlterField(
            model_name="workingtime",
            name="end_time",
            field=models.TimeField(verbose_name="Tugash vaqti"),
        ),
        migrations.AlterField(
            model_name="workingtime",
            name="start_time",
            field=models.TimeField(verbose_name="Boshlanish vaqti"),
        ),
        migrations.AlterField(
            model_name="workingtime",
            name="weekday",
            field=models.CharField(max_length=30, verbose_name="Hafta kuni"),
        ),
        migrations.AlterField(
            model_name="workingtime",
            name="weekday_en",
            field=models.CharField(
                max_length=30, null=True, verbose_name="Hafta kuni"
            ),
        ),
        migrations.AlterField(
            model_name="workingtime",
            name="weekday_ru",
            field=models.CharField(
                max_length=30, null=True, verbose_name="Hafta kuni"
            ),
        ),
        migrations.AlterField(
            model_name="workingtime",
            name="weekday_uz",
            field=models.CharField(
                max_length=30, null=True, verbose_name="Hafta kuni"
            ),
        ),
        migrations.AlterField(
            model_name="workingtime",
            name="weekday_uz_Cyrl",
            field=models.CharField(
                max_length=30, null=True, verbose_name="Hafta kuni"
            ),
        ),
    ]
