# Generated by Django 5.0.8 on 2024-08-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0031_alter_about_options_alter_address_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
    ]
