# Generated by Django 5.0.8 on 2024-08-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0032_gallery_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
    ]
