# Generated by Django 5.1 on 2024-09-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0033_image_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Matn")),
                ("text_uz", models.TextField(null=True, verbose_name="Matn")),
                (
                    "text_uz_Cyrl",
                    models.TextField(null=True, verbose_name="Matn"),
                ),
                ("text_ru", models.TextField(null=True, verbose_name="Matn")),
                ("text_en", models.TextField(null=True, verbose_name="Matn")),
            ],
            options={
                "verbose_name": "Narx matni",
                "verbose_name_plural": "Narx matnlari",
            },
        ),
    ]
