# Generated by Django 5.1 on 2024-09-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0034_pricetext"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibit",
            name="size_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="O'lcham"
            ),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="size_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="O'lcham"
            ),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="size_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="O'lcham"
            ),
        ),
        migrations.AddField(
            model_name="exhibit",
            name="size_uz_Cyrl",
            field=models.CharField(
                max_length=255, null=True, verbose_name="O'lcham"
            ),
        ),
    ]
