# Generated by Django 5.1 on 2024-09-05 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "museum",
            "0035_exhibit_size_en_exhibit_size_ru_exhibit_size_uz_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exhibit",
            name="size",
        ),
        migrations.RemoveField(
            model_name="exhibit",
            name="size_en",
        ),
        migrations.RemoveField(
            model_name="exhibit",
            name="size_ru",
        ),
        migrations.RemoveField(
            model_name="exhibit",
            name="size_uz",
        ),
        migrations.RemoveField(
            model_name="exhibit",
            name="size_uz_Cyrl",
        ),
    ]
