# Generated by Django 5.1 on 2024-09-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0036_remove_exhibit_size_remove_exhibit_size_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usefulcontent",
            name="url_name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="URL nomi"
            ),
        ),
        migrations.AddField(
            model_name="usefulcontent",
            name="url_name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="URL nomi"
            ),
        ),
        migrations.AddField(
            model_name="usefulcontent",
            name="url_name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="URL nomi"
            ),
        ),
        migrations.AddField(
            model_name="usefulcontent",
            name="url_name_uz_Cyrl",
            field=models.CharField(
                max_length=255, null=True, verbose_name="URL nomi"
            ),
        ),
    ]
