# Generated by Django 5.1 on 2024-09-19 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "museum",
            "0037_usefulcontent_url_name_en_usefulcontent_url_name_ru_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usefulcontent",
            name="url_name_en",
        ),
        migrations.RemoveField(
            model_name="usefulcontent",
            name="url_name_ru",
        ),
        migrations.RemoveField(
            model_name="usefulcontent",
            name="url_name_uz",
        ),
        migrations.RemoveField(
            model_name="usefulcontent",
            name="url_name_uz_Cyrl",
        ),
    ]
