# Generated by Django 5.1 on 2024-09-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0038_remove_usefulcontent_url_name_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="management",
            name="description",
        ),
        migrations.RemoveField(
            model_name="management",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="management",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="management",
            name="description_uz",
        ),
        migrations.RemoveField(
            model_name="management",
            name="description_uz_Cyrl",
        ),
    ]
